In [ ]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
#printing the stopwords
from nltk.corpus import stopwords
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

#DATA PREPROCESSING


1.   LOADING THE DATA SET IN PANDAS DATAFRAME
2.

In [ ]:
#LOADING THE DATA SET
news_dataset=pd.read_csv('/content/train.csv')

#checking the number of rows and colums
news_dataset.shape

#printing the first 5 rows and coloums
news_dataset.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [ ]:
#counting the number of missing values
news_dataset.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [ ]:
#replacing the null values with empty string
news_dataset=news_dataset.fillna('')

In [ ]:
#merging the two  coloums author and tirtle
news_dataset["content"]=news_dataset["author"]+""+news_dataset["title"]
print(news_dataset["content"])

0        Darrell LucusHouse Dem Aide: We Didn’t Even Se...
1        Daniel J. FlynnFLYNN: Hillary Clinton, Big Wom...
2        Consortiumnews.comWhy the Truth Might Get You ...
3        Jessica Purkiss15 Civilians Killed In Single U...
4        Howard PortnoyIranian woman jailed for fiction...
                               ...
20795    Jerome HudsonRapper T.I.: Trump a ’Poster Chil...
20796    Benjamin HoffmanN.F.L. Playoffs: Schedule, Mat...
20797    Michael J. de la Merced and Rachel AbramsMacy’...
20798    Alex AnsaryNATO, Russia To Hold Parallel Exerc...
20799               David SwansonWhat Keeps the F-35 Alive
Name: content, Length: 20800, dtype: object

In [ ]:
#seperating the data annd labels coloums
X=news_dataset.drop(columns="label",axis=1)
Y=news_dataset["label"]

In [ ]:
print(X)
print(Y)

          id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...
2          2                  Why the Truth Might Get You Fired
3          3  15 Civilians Killed In Single US Airstrike Hav...
4          4  Iranian woman jailed for fictional unpublished...
...      ...                                                ...
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797  20797  Macy’s Is Said to Receive Takeover Approach by...
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799  20799                          What Keeps the F-35 Alive

                                          author  \
0                                  Darrell Lucus
1                                Daniel J. Flynn
2                             Consortiumnews.com
3                                Jessica Purkiss
4                                 Howard Portnoy
...                                          ...
20795                              Jerome Hudson
20796                           Benjamin Hoffman
20797  Michael J. de la Merced and Rachel Abrams
20798                                Alex Ansary
20799                              David Swanson

                                                    text  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...
1      Ever get the feeling your life circles the rou...
2      Why the Truth Might Get You Fired October 29, ...
3      Videos 15 Civilians Killed In Single US Airstr...
4      Print \nAn Iranian woman has been sentenced to...
...                                                  ...
20795  Rapper T. I. unloaded on black celebrities who...
20796  When the Green Bay Packers lost to the Washing...
20797  The Macy’s of today grew from the union of sev...
20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799    David Swanson is an author, activist, journa...

                                                 content
0      Darrell LucusHouse Dem Aide: We Didn’t Even Se...
1      Daniel J. FlynnFLYNN: Hillary Clinton, Big Wom...
2      Consortiumnews.comWhy the Truth Might Get You ...
3      Jessica Purkiss15 Civilians Killed In Single U...
4      Howard PortnoyIranian woman jailed for fiction...
...                                                  ...
20795  Jerome HudsonRapper T.I.: Trump a ’Poster Chil...
20796  Benjamin HoffmanN.F.L. Playoffs: Schedule, Mat...
20797  Michael J. de la Merced and Rachel AbramsMacy’...
20798  Alex AnsaryNATO, Russia To Hold Parallel Exerc...
20799             David SwansonWhat Keeps the F-35 Alive

[20800 rows x 5 columns]
0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

#STEAMMING
steamming is the process of reducing a word to its root word likke removiing the prefix and sufixes of different words

we will be using porter streamming for this

In [ ]:
port_stem= PorterStemmer()

In [ ]:
def stemming(content):
  stemmed_content=re.sub('[^a-zA-Z]',' ',content)
  stemmed_content=stemmed_content.lower()
  stemmed_content=stemmed_content.split()
  stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content=' '.join(stemmed_content)
  return stemmed_content

In [ ]:
#now we will apply this function to our coloums
news_dataset['content']=news_dataset['content'].apply(stemming)

In [ ]:
print(news_dataset['content'])

0        darrel lucushous dem aid even see comey letter...
1        daniel j flynnflynn hillari clinton big woman ...
2                consortiumnew comwhi truth might get fire
3        jessica purkiss civilian kill singl us airstri...
4        howard portnoyiranian woman jail fiction unpub...
                               ...
20795    jerom hudsonrapp trump poster child white supr...
20796    benjamin hoffmann f l playoff schedul matchup ...
20797    michael j de la merc rachel abramsmaci said re...
20798    alex ansarynato russia hold parallel exercis b...
20799                        david swansonwhat keep f aliv
Name: content, Length: 20800, dtype: object

In [ ]:
#seperating the data and lables
X=news_dataset['content'].values
Y=news_dataset['label'].values

In [ ]:
print(X)
print(Y)

['darrel lucushous dem aid even see comey letter jason chaffetz tweet'
 'daniel j flynnflynn hillari clinton big woman campu breitbart'
 'consortiumnew comwhi truth might get fire' ...
 'michael j de la merc rachel abramsmaci said receiv takeov approach hudson bay new york time'
 'alex ansarynato russia hold parallel exercis balkan'
 'david swansonwhat keep f aliv']

In [ ]:
#seperating the data and lables
X=news_dataset['content'].values
#converting textual data to numerical data
vectorizer=TfidfVectorizer()
X = vectorizer.fit_transform(X)
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 198373 stored elements and shape (20800, 28419)>
  Coords	Values
  (0, 5969)	0.35488202138141456
  (0, 15019)	0.43006226759639316
  (0, 6273)	0.2839932825877813
  (0, 578)	0.2694167078545385
  (0, 8022)	0.23133661742488731
  (0, 22724)	0.2552336018069161
  (0, 5006)	0.2472595823572816
  (0, 14555)	0.29177259684200296
  (0, 12782)	0.24619727512767195
  (0, 4211)	0.3625320323150658
  (0, 26340)	0.28088379401596425
  (1, 5916)	0.3181005810963805
  (1, 8772)	0.525863562538645
  (1, 11313)	0.24166773097712632
  (1, 4767)	0.23338756776626787
  (1, 2622)	0.3562953366945266
  (1, 27923)	0.3691184595384501
  (1, 3859)	0.45980466668763464
  (1, 3281)	0.18652439327549422
  (2, 5240)	0.40440534260277944
  (2, 5121)	0.5511414848555652
  (2, 26235)	0.3665032495181434
  (2, 16361)	0.43295215406038445
  (2, 9454)	0.30743020569262086
  (2, 8567)	0.3411947414020896
  :	:
  (20797, 28256)	0.08325516659943971
  (20797, 25776)	0.08220218573989037
  (20797, 16315)	0.1785200594251359
  (20797, 6088)	0.21253094503918346
  (20797, 14104)	0.22761807337911874
  (20797, 20493)	0.249994989010826
  (20797, 11692)	0.2992170910232368
  (20797, 25319)	0.3119640221826561
  (20797, 20778)	0.2729578683228216
  (20797, 22086)	0.24902354987792552
  (20797, 2257)	0.3357782642976524
  (20797, 1249)	0.3072223353708335
  (20797, 16217)	0.3273246827604847
  (20797, 72)	0.38829670969848273
  (20798, 21937)	0.2284042880065583
  (20798, 11434)	0.3219420705942853
  (20798, 18760)	0.43981843518920394
  (20798, 697)	0.2827933658592677
  (20798, 8095)	0.40266358130888547
  (20798, 1921)	0.43981843518920394
  (20798, 1081)	0.4638903157542853
  (20799, 13329)	0.4138037375613909
  (20799, 6018)	0.345590335823275
  (20799, 732)	0.5085743925573473
  (20799, 25148)	0.6713314187498636

In [ ]:
#splitting the data into  training and test data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, stratify=Y , random_state=2)

In [ ]:
#training the model
model=LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

Evaluation
accuracy score

In [ ]:
#accuracy score of the training data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print("accuracy score of the training data",training_data_accuracy)

accuracy score of the training data 0.971875

In [ ]:
#accuracy score of the test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print("accuracy score of the test data",test_data_accuracy)

accuracy score of the test data 0.9550480769230769

#Making a predictivve system

In [ ]:
X_new =X_test[0]
prediction= model.predict(X_new)
print(prediction)
if (prediction[0]==0):
  print("the news is real :")
else:
  print("the news is fake ")

print(Y_test[0])

[1]
the news is fake
1